import pyautogui as aut
usuario = input("Qual seu usuario do instagram:")
senha = input("Qual sua senha do insta:") 

aut.mouseInfo()
aut.press("win")
aut.sleep(2)
aut.write("instagram")
aut.press("enter")
aut.moveTo(1582,456)
aut.sleep(1)    
aut.click()
aut.sleep(2)
aut.moveTo(219,447)
aut.sleep(2)
aut.click()
aut.sleep(2)
aut.press("tab")
aut.sleep(1)
aut.write(f"{usuario}")
aut.sleep(2)
aut.moveTo(1163,439)
aut.sleep(1)
aut.click()
aut.sleep(2)
aut.write(f"{senha}")
aut.sleep(2)
aut.moveTo(1218,488)
aut.click()

